FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bluez bluetooth dbus libdbus-1-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY bridge_ble_ws.py ./

CMD ["python", "-u", "bridge_ble_ws.py"]
